version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: avenuecode_db
    environment:
      POSTGRES_DB: avenuecode_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
